### ISSUE TITLE
Magic > Rare > Unique Jewel Recipe missing

### ISSUE THREAD

**Issue by Bakelt** [D2R-Reimagined/d2r-reimagined-mod#124]

**Comment by brinza666** [comment]
Hey,
First of all, thx to all who is working on the mod. It brought me back into game.
I'm experiencing same issue.
Tried to combine 9 magic = nothing happening 
Tried to combine 9 rare jewels = nothing 
Farmed 9 magic in new update 1.20 and try cubbing, still nothing.

Maybe im doing something wrong? Followed text from release page ...

BTW:

Thank you in advance for looking into it as i still didn't got any unique jewels since i'v started playing= 3 days, lvl99, got already all rarest items in game, but still no unique jewels. I was excited with the news it could be obtained by combining :/

**Comment by brinza666** [comment]
Fixed in last update
