### ISSUE TITLE
Missing String for a magic affix

### ISSUE THREAD

**Issue by Bakelt** [D2R-Reimagined/d2r-reimagined-mod#204]
I believe the new repair+ethereal is the culprit
![image](https://github.com/user-attachments/assets/143b904f-1144-416b-a7f4-07310bce6644)

**Comment by victoria-riley-barnett** [comment]
It's name (Ghostly1) as well as several other ones is shared with the eth/rep-dur/att% mod - could that be the issue?

**Comment by victoria-riley-barnett** [comment]
Also unsure if these names need to be referenced elsewhere, data guide not clear on that it makes it sound independent

**Comment by Delegus** [comment]
Many of these have numbers (which can be safely just be removed as long as they reference a valid stat) or reference an invalid stat entirely that doesn't exist in properties or itemstatcost; ex attribute % (so I marked them as not spawnable instead of removing and messing up the rows) I have been playing (leveled a paladin 1 to 99) since making a rough change to my own files but haven't updated a Git branch for it yet in case someone knows more than just me investigating; Maybe a holdover of the mod merge that wasn't included in the string json files.
